version: "3.11"

services:
  web:
    build: .
    container_name: fastapi_app
    command: uvicorn main:app --reload --workers 1 --host
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:alpine
    container_name: fastapi_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: dbtest
